spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  docker:
    compose:
      enabled: false
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 1m
      file: ./redis-various-ways/compose.yaml