services:
  local-aws:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PORT_WEB_UI=8080
      - AWS_DEFAULT_REGION=ap-northeast-2
      - USE_SSL=0
    ports:
      - 4566:4566
    volumes:
      - ./scripts/create-local-s3-bucket.sh:/etc/localstack/init/ready.d/init-aws.sh