spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    hikari:
      maximum-pool-size: 20001
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 1m
      file: ./redis-concurrency-lock/compose.yaml

