services:
  mysql:
    image: "mysql:latest"
    environment:
      - 'MYSQL_ROOT_PASSWORD=rootsecret'
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=mysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
