spring:
  application:
    name: spring-kafka-event
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/springkafkaevent
    username: sa
    password:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: spring-kafka-event
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false