spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
  datasource:
    hikari:
      maximum-pool-size: 20001
